version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: dotnetbase-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dotnetbase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dotnetbase-network

  redis:
    image: hub.hamdocker.ir/library/redis:latest
    container_name: dotnetbase-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dotnetbase-network

  redisinsight:
    image: redis/redisinsight:latest
    container_name: dotnetbase-redisinsight
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/data
    networks:
      - dotnetbase-network
    depends_on:
      - redis

volumes:
  postgres_data:
  redis_data:
  redisinsight_data:

networks:
  dotnetbase-network:
    driver: bridge
